# Site Settings
lang: en
title: Georgia Anderson
tagline: Franklin and Marshall, Physics '23
email: geoba2013@gmail.com
description: >
  Georgia Anderson description
permalink: pretty
#favicon: /path/to/favicon.png
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
remote_theme: chrisrhymes/bulma-clean-theme
#paginate: 5
#paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: georgiande


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "Resume"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "Projects"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
